[package]
name = "btcnetmsg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.1"
rand = "0.8.4"
bitcoin = "0.27.1"